### ISSUE TITLE
Open Source embedding - Nomic

### ISSUE THREAD

**Issue by AltayYuzeir** [developersdigest/llm-answer-engine#10]
Hello. Thank you for open sourcing this awesome tool.
I was watching the video by [Matthew Berman](https://www.youtube.com/watch?v=GanTUWLUUWQ) and he suggested to improve the open source nature of the project by replacing the OpenAI embedding with the open source [Nomic](https://blog.nomic.ai/posts/nomic-embed-text-v1) embedding.

**Comment by ipty** [comment]
you can change the settings in /app/config.tsx
https://github.com/developersdigest/llm-answer-engine/blob/main/app/config.tsx

hope it helps
erik

**Comment by developersdigest** [comment]
thanks for the rely @ipty , @AltayYuzeir I can confirm that nomic and local embeddings do work. If you are going to use local embedding models while also using a local chat completions, time-to-first-token can increase considerably depending on your machine. I recommend decreasing the values associated with the RAG process at the bottom of the config when using local inference. cheers!
