### ISSUE TITLE
Text and background same color

### ISSUE THREAD

**Issue by lafintiger** [developersdigest/llm-answer-engine#12]
Looks like nothing is there until you highlight it.

**Comment by muellercodes** [comment]
Oh yep I am getting the same thing. My Mac's system is set to dark and there is an issue with dark mode vs light mode it seems. It's the `prefers-color-scheme` media query.

**Comment by itsaark** [comment]
@muellercodes Where you able to fix it? What changes did you make? I'm having the same issue

**Comment by developersdigest** [comment]
thank you all for bringing this up! i turned on dark mode and am working on a fix rn, will merge shortly.

**Comment by itsaark** [comment]
Thanks @developersdigest You are the GOAT

**Comment by developersdigest** [comment]
Thanks again to everyone who pointed this out!

![Example](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDQxdHR0NWc4MHl6cDBsNmpiMGNyeWNwbnE4MjZlb29oZGRsODBhMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/QjINYAx6le5PMY020A/giphy.gif)

**Comment by AmoghSaxena** [comment]
@developersdigest 

Mine look like this 
![image](https://github.com/user-attachments/assets/3a5ed9c5-e08c-4eca-9165-0b01d1d16dad)


I dont know the text input box is not rounded. Its square instead. Also how can I turn on the light mode?
Maybe my display is OLED thats why this dark theme doesnt look good on it. 

![image](https://github.com/user-attachments/assets/7efbe4e9-7710-409e-a76b-6b4d0d365c68)
