### ISSUE TITLE
Please create a docker image for this repo

### ISSUE THREAD

**Issue by kneelesh48** [developersdigest/llm-answer-engine#16]
Please create a docker image for this repo making it extremely easy for new comers to deploy this project on their own server

I can send a pull request with a dockerfile and a docker-compose.yml file. Let me know if you're up.

**Comment by developersdigest** [comment]
Thank you! A PR existed for this as well #15 it has now been merged.

**Comment by kneelesh48** [comment]
It's better to host the docker image on docker hub or GitHub container repository (ghcr) so the user doesn't have to build the image, they can just download it. Even though the build is automatic, it takes longer.

Also, we can add steps to install via docker in the readme

**Comment by arsaboo** [comment]
Indeed, it makes it significantly easier for new users to get started if the docker image is provided, and users can just run a docker command (or use a compose file) without going through the build process. 

@developersdigest can we please look into this...thanks!
