### ISSUE TITLE
Please add LiteLLM to this project

### ISSUE THREAD

**Issue by HakaishinShwet** [developersdigest/llm-answer-engine#23]
This project is pretty great BUT we need more options to use different LLM's.You don't have to worry about creating a solution which supports 100+ LLM easily as LiteLLM is another foss project which is capable of doing this task for you.
Project LiteLLM link - https://github.com/BerriAI/litellm
Adding LiteLLM will be big win for the project as many will be easily able to use many more LLM easily which everyone wants and project will require 3 major parameters from user like base url,model name,api key that's all and with open ai api general structure it can query and give back result for the query.Many big projects have started adding support for this project in there project to make things advanced in easier way so study it and after that if you have any query you can ask them they are pretty responsive plus if u want to know more about my personal experience of using it with other great projects like flowise then I can tell you that too in detail.

**Comment by developersdigest** [comment]
Thank you - I am currently working on a few new features that I will be adding hopefully this weekend. 
Once those are done, I will take a closer look at this. Great suggestion.

**Comment by HakaishinShwet** [comment]
@developersdigest nice :-)) hope to see great development in this awesome project

**Comment by developersdigest** [comment]
Circling back to this - to accomplish that I am planning on adding AI Gateway instead of LiteLLM

AI Gateway has support for the following: OpenAI, Azure OpenAI, Anyscale, Google Gemini & Palm, Anthropic, Cohere, Together AI, Perplexity, Mistral, Nomic, AI21, Stability AI, DeepInfra, Ollama and more. 

More details here: https://github.com/Portkey-AI/gateway

Thank you for your support and sparking this idea!

**Comment by NeverOccurs** [comment]
> Circling back to this - to accomplish that I am planning on adding AI Gateway instead of LiteLLM
> 
> AI Gateway has support for the following: OpenAI, Azure OpenAI, Anyscale, Google Gemini & Palm, Anthropic, Cohere, Together AI, Perplexity, Mistral, Nomic, AI21, Stability AI, DeepInfra, Ollama and more.
> 
> More details here: https://github.com/Portkey-AI/gateway
> 
> Thank you for your support and sparking this idea!

Why Gateway instead of LiteLLM?
