### ISSUE TITLE
Update to Vercel AI SDK 3.0

### ISSUE THREAD

**Issue by itsaark** [developersdigest/llm-answer-engine#24]
Would be awesome if you could update to the new AI SDK version with all the neat features 
https://vercel.com/blog/ai-sdk-3-generative-ui

**Comment by developersdigest** [comment]
Hey @itsaark, I started building this shortly after the AI SDK 3.0 came out, you are able to pull in any of the new APIs within their new SDK. I will be releasing some new UI components hopefully this weekend with some more examples - Cheers!
