### ISSUE TITLE
Brave API is costly so can we use serper API alone instead ?

### ISSUE THREAD

**Issue by anoobn** [developersdigest/llm-answer-engine#27]
Can we use Serper AI API instead of Brave API which is relatively costly ,kindly give views on the feasibility.

**Comment by developersdigest** [comment]
Absolutely.

**Comment by anoobn** [comment]
> Absolutely.

Thanks a lot for your reply  ,so you are saying we can use Serper API in both the places right ?

**Comment by developersdigest** [comment]
It would take a little bit of refactoing just around the portion around the brave search query to normalize the responses to make them compatible with the current set up.

For example you could swap out BraveSearch query logic for something along these lines to be compatible with Brave.

fetch('https://google.serper.dev/search', {
  method: 'post',
  headers: {
    'X-API-KEY': 'API_KEY_GOES_HERE',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({ "q": "apple inc" })
})
  .then(response => response.json())
  .then(data => console.log(JSON.stringify(data)))
  .catch(error => console.log(error));
  
 I plan on eventually supporting different methods for search - I just unfortunately don't have an ETA on when I will be able to implement the different search requests quite yet.

**Comment by anoobn** [comment]
that works ,thanks a lot!
