### ISSUE TITLE
Can I only use GPT's API?

### ISSUE THREAD

**Issue by ifhjl** [developersdigest/llm-answer-engine#38]
Because I don't have a credit card which means for Brave and the below one i can't get their api key for free, can i use this repo without it?

**Comment by EnderRobber101** [comment]
If you know how to code, you can edit it to use google's api key which has a limit of 100 calls/day on a free tier.

**Comment by developersdigest** [comment]
Thanks for pointing that out - and great idea about the google search api as an option. I will try and add in some different options for search providers so there is more flexibility. 

Google is an option, Serper also does have a credit card free option for the search queries as well.

**Comment by developersdigest** [comment]
I have added in support for the google api and the serper api as options in the config
