### ISSUE TITLE
how to use my own openai proxy?

### ISSUE THREAD

**Issue by HelloEveryonehh** [developersdigest/llm-answer-engine#46]
Thank you for the author's contribution in creating such an excellent project. I would like to ask how I can replace OpenAI's API with my own OpenAI proxy?

**Comment by developersdigest** [comment]
In the config.tsx just update this key to your OpenAI Proxy

nonOllamaBaseURL: 'https://api.groq.com/openai/v1', //Groq: https://api.groq.com/openai/v1 // OpenAI: https://api.openai.com/v1
