### ISSUE TITLE
Open source embeddings

### ISSUE THREAD

**Issue by manas95826** [developersdigest/llm-answer-engine#49]
Anyhow, I've to use openai embeddings for this. Can anyone provide any lead to use open source embeddings instead to make it completely open source.

**Comment by developersdigest** [comment]
You can use open source embeddings via Ollama embeddings: https://ollama.com/blog/embedding-models. Just update the config.tsx with the models you'd like to use

**Comment by manas95826** [comment]
Thanks a lot for this. Why is it demanding openai api key now then?

**Comment by developersdigest** [comment]
Should have mentioned - Ollama required an apiKey even though it isn't used. Try adding: 'ollama' as the api key.

More info: https://ollama.com/blog/openai-compatibility
