### ISSUE TITLE
Open Ai API

### ISSUE THREAD

**Issue by cathaldempsey** [developersdigest/llm-answer-engine#5]
There is another open ai api key being set , removed my own from .env and another still being set - my configuration or being dynamically set somewhere else in the code ?

**Comment by oliviermills** [comment]
This code version uses GROQ (see the index file) .. so you need to get a GROQ key GROQ_API_KEY .. or adjust the code to take the OPEN_AI key

**Comment by developersdigest** [comment]
Thanks for responding to this one @oliviermills !
